# Generated by Django 3.2.4 on 2024-03-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
    ]
