# Generated by Django 3.2.4 on 2024-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='product_image', to='products.ProductImage'),
        ),
    ]
