# Generated by Django 3.2.4 on 2024-03-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
