# Generated by Django 3.2.4 on 2024-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240309_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Author name'),
        ),
    ]
