# Generated by Django 3.2.4 on 2024-03-10 07:40

from django.db import migrations, models
import products.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=products.utilities.category_image_path),
        ),
    ]
