# Generated by Django 3.2.4 on 2024-03-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20240310_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
    ]
