# Generated by Django 3.2.4 on 2024-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('page', 'Page'), ('blog', 'Blog')], default='blog', max_length=10),
        ),
    ]
