# Generated by Django 3.2.4 on 2024-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
