# Generated by Django 3.2.4 on 2024-04-07 14:33

from django.db import migrations, models
import products.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20240407_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to=products.utilities.blogs_image_path),
        ),
    ]
