# Generated by Django 3.2.4 on 2024-04-07 15:15

from django.db import migrations, models
import products.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_post_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_paragraph',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to=products.utilities.blogs_post_image_path),
        ),
    ]
