# Generated by Django 3.2.4 on 2024-04-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20240407_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtype',
            field=models.CharField(blank=True, choices=[('review', 'Review'), ('release', 'Release')], max_length=10, null=True),
        ),
    ]
