# Generated by Django 3.2.4 on 2024-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_paragraph',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
