# Generated by Django 3.2.4 on 2024-03-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240324_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('D', 'cancelled')], default='P', max_length=1),
        ),
    ]
