# Generated by Django 3.2.4 on 2024-03-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('X', 'cancelled'), ('D', 'delete')], default='P', max_length=1),
        ),
    ]
