# Generated by Django 3.2.4 on 2024-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_post_post_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
