# Generated by Django 3.2.4 on 2024-03-25 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20240324_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Avatar',
        ),
    ]
